from __future__ import annotations

from pathlib import Path

import numpy as np

from ..core.molecule import Molecule

__all__ = ["XYZFormatError", "read_xyz", "write_xyz"]


class XYZFormatError(ValueError):
    """Raised when an XYZ file is malformed."""


def read_xyz(file_path: str | Path, *, strict: bool = True) -> Molecule:
    """
    Read an XYZ file (先頭の1構造のみ).

    XYZ format (typical):
      line1: integer atom count
      line2: comment
      line3..: "Element x y z" (at least 4 columns)

    If strict=True, 4列未満の行や原子数の不一致をエラーにする。
    """
    path = Path(file_path)

    try:
        with path.open("r", encoding="utf-8") as f:
            first = f.readline()
            if not first.strip():
                raise XYZFormatError("Empty file or missing atom count")

            try:
                n_expected = int(first.split()[0])
            except ValueError as e:
                raise XYZFormatError(
                    f"First line must be atom count int, got: {first!r}"
                ) from e

            f.readline()  # comment line (ignored)

            atoms: list[str] = []
            coords_list: list[list[float]] = []

            for lineno, line in enumerate(f, start=3):
                if len(atoms) >= n_expected:
                    break  # 複数構造の xyz でも最初の構造だけ読む

                s = line.strip()
                if not s:
                    continue  # allow blank lines
                parts = s.split()
                if len(parts) < 4:
                    if strict:
                        raise XYZFormatError(
                            f"Line {lineno}: expected 'Atom x y z', got: {line!r}"
                        )
                    continue

                try:
                    x, y, z = float(parts[1]), float(parts[2]), float(parts[3])
                except ValueError as e:
                    raise XYZFormatError(
                        f"Line {lineno}: non-numeric coordinate in: {line!r}"
                    ) from e

                atoms.append(parts[0])
                coords_list.append([x, y, z])

    except FileNotFoundError as e:
        raise FileNotFoundError(f"XYZ file not found: {path}") from e

    if strict and len(atoms) != n_expected:
        raise XYZFormatError(
            f"Atom count mismatch: header={n_expected}, parsed={len(atoms)}"
        )

    coord = np.asarray(coords_list, dtype=float).reshape(-1, 3)
    return Molecule(atoms=atoms, coord=coord)


def write_xyz(
    file_path: str | Path,
    *,
    mole: Molecule,
    comment: str = "Generated by yaoyorozu",
) -> None:
    path = Path(file_path)

    # Molecule 側で検証済みだが、後から属性が差し替えられた場合に備えて再確認
    coords = np.asarray(mole.coord, dtype=float)
    if coords.ndim != 2 or coords.shape[1] != 3:
        raise ValueError(f"coords must be (N,3), got {coords.shape}")
    if len(mole.atoms) != len(coords):
        raise ValueError(
            f"Atom/coord mismatch: {len(mole.atoms)} vs {len(coords)}"
        )

    with path.open("w", encoding="utf-8") as f:
        f.write(f"{len(mole.atoms)}\n")
        f.write(f"{comment}\n")
        for atom, (x, y, z) in zip(mole.atoms, coords):
            f.write(f"  {atom:<2} {x:18.10f} {y:18.10f} {z:18.10f}\n")
