from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable
import numpy as np


class XYZFormatError(ValueError):
    """Raised when an XYZ file is malformed."""


@dataclass(frozen=True)
class MOLECULE:
    atoms: list[str]
    coord: np.ndarray  # shape (N, 3), dtype float
    def __post_init__(self):
        coord = np.asarray(self.coord, dtype=float)

        if coord.ndim != 2 or coord.shape[1] != 3:
            raise ValueError(f"coords must be (N,3), got {coord.shape}")

        if len(self.atoms) != len(coord):
            raise ValueError(
                f"Atom/coord mismatch: {len(self.atoms)} vs {len(coord)}"
            )

        # frozen=True なので object.__setattr__ を使う
        object.__setattr__(self, "coord", coord.copy())
        object.__setattr__(self, "atoms", list(self.atoms))


def read_xyz(file_path: str | Path, *, strict: bool = True) -> MOLECULE:
    """
    Read an XYZ file.

    XYZ format (typical):
      line1: integer atom count
      line2: comment
      line3..: "Element x y z" (at least 4 columns)

    If strict=True, validates atom count and coordinate shape.
    """
    path = Path(file_path)

    try:
        with path.open("r", encoding="utf-8") as f:
            first = f.readline()
            if not first:
                raise XYZFormatError("Empty file")

            try:
                n_expected = int(first.strip())
            except ValueError as e:
                raise XYZFormatError(f"First line must be atom count int, got: {first!r}") from e

            _comment = f.readline()  # comment line may be empty; we ignore it

            atoms: list[str] = []
            coords_list: list[list[float]] = []

            for lineno, line in enumerate(f, start=3):
                s = line.strip()
                if not s:
                    continue  # allow blank lines
                parts = s.split()
                if len(parts) < 4:
                    if strict:
                        raise XYZFormatError(f"Line {lineno}: expected 'Atom x y z', got: {line!r}")
                    else:
                        continue

                atom = parts[0]
                try:
                    x, y, z = (float(parts[1]), float(parts[2]), float(parts[3]))
                except ValueError as e:
                    raise XYZFormatError(f"Line {lineno}: non-numeric coordinate in: {line!r}") from e

                atoms.append(atom)
                coords_list.append([x, y, z])

    except FileNotFoundError as e:
        raise FileNotFoundError(f"XYZ file not found: {path}") from e

    coord = np.asarray(coords_list, dtype=float)

    if coord.ndim != 2 or coord.shape[1] != 3:
        raise XYZFormatError(f"Coordinates must be Nx3, got shape={coord.shape}")

    if strict and len(atoms) != n_expected:
        raise XYZFormatError(f"Atom count mismatch: header={n_expected}, parsed={len(atoms)}")

    return MOLECULE(atoms=atoms, coord=coord)

def write_xyz(file_path: str | Path, *, mole: MOLECULE, comment: str = "Generated by yaoyorozu") -> None:
    path = Path(file_path)

    coords = np.asarray(mole.coord, dtype=float)

    if coords.ndim != 2 or coords.shape[1] != 3:
        raise ValueError(f"coords must be (N,3), got {coords.shape}")

    if len(mole.atoms) != len(coords):
        raise ValueError(
            f"Atom/coord mismatch: {len(xyz.atoms)} vs {len(coords)}"
        )

    with path.open("w", encoding="utf-8") as f:
        f.write(f"{len(mole.atoms)}\n")
        f.write(f"{comment}\n")

        for atom, (x, y, z) in zip(mole.atoms, coords):
            f.write(f"  {atom:<2} {x:18.10f} {y:18.10f} {z:18.10f}\n")

def kabsch(*, target: MOLECULE, ref: MOLECULE) -> MOLECULE: 
    P = np.array(target.coord)
    Q = np.array(ref.coord)

    Pg = np.mean(P, axis=0)
    Qg = np.mean(Q, axis=0)

    P = P - Pg
    Q = Q - Qg

    C = np.dot(P.T,Q)
    V, S, Wt = np.linalg.svd(C)
    d = np.sign(np.linalg.det(np.dot(V, Wt)))
    D = np.diag([1, 1, d]) 
    U = np.dot(np.dot(V, D), Wt) 
    P=P@U

    P = P + Qg
    mole = MOLECULE(atoms=target.atoms,coord=P)

    return mole


def rotate(*, mole: MOLECULE, R: np.ndarray) -> MOLECULE:
    R = np.asarray(R, dtype=float)
    if R.shape != (3, 3):
        raise ValueError(f"R must be 3x3, got {R.shape}")

    coord = mole.coord @ R.T   # (N,3) @ (3,3) -> (N,3)
    return MOLECULE(atoms=mole.atoms, coord=coord)



def measure_geometry(*, mole: MOLECULE, index: index) -> float:
    xyz = mole.coord
    if len(index) == 2:    # bond length
        i, j = index[0], index[1]
        vec = xyz[i] - xyz[j]
        return np.linalg.norm(vec)
        
    elif len(index) == 3:  # angle
        i, j, k = index[0],index[1],index[2]
        vec1 = np.array(xyz[i]) - np.array(xyz[j])
        vec2 = np.array(xyz[k]) - np.array(xyz[j])
        cos_theta = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))

        cos_theta = np.clip(cos_theta, -1.0, 1.0)
        return np.degrees(np.arccos(cos_theta))
        
    else:
        raise ValueError("Indices must be a tuple of 2 (for bond length) or 3 (for angle).")
